name: Daily File Update

permissions:
  contents: write

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update file
        run: |
          echo "Last updated: $(date -u +%s%N)" > daily-update.txt

      - name: Set Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit and Push
        run: |
          git add daily-update.txt
          git commit -m "Auto update: $(date -u)" || echo "⚠ Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
